version: '3.8'

services:
  server:
    container-name: server
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    expose:
      - "9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    user: '1000'
    #volumes:
    #  - ./grafana_data:/var/lib/grafana
